### PR TITLE
feat: restructure rules used and simplify tflint config

### LINKED ISSUE #1: Setting individual terraform rules compared to using terraform plugin with recommended settings
In our tflint config file we specify the 16 terraform rules available, which are:
- terraform_comment_syntax
- **terraform_deprecated_index**
- **terraform_deprecated_interpolation**
- terraform_documented_outputs
- terraform_documented_variables
- **terraform_empty_list_equality**
- **terraform_module_pinned_source**
- **terraform_module_version** 
- terraform_naming_convention
- **terraform_required_providers**
- **terraform_required_version**
- terraform_standard_module_structure
- **terraform_typed_variables**
- **terraform_unused_declarations**
- terraform_unused_required_providers
- **terraform_workspace_remote**

The one marked **bold** are part of the "recommended" presets that can be used with the terraform plugin
``` hcl
plugin "terraform" {
  enabled = true
  preset  = "recommended"
}
```

So why do we set the rules explicitly instead of using the recommended settings with the plugin? Also, should we use the optional  rules that are not part of the recommended preset all the time or should we mark them optional in our tflint configuration as well?

To me using the terraform plugin has a few advantages above defining the rules individually:
1. easier maintenenace: We always follow the recommended ruleset and don't have to regularly update individual rules
2. following best practices: We always follow the recommended ruleset

@mhmdio what's your opinion on this?

### PR DESCRIPTION
**Pull request by sthuber90**
update documentation and fix broken links

Closes #1

### CODE REVIEW

**Comment by mhmdio** [comment]
@sthuber90 Can we create a new `tflint-module.hcl` and keep the module's rules? or create `.tflint-all.hcl` with all rules

**Comment by sthuber90** [comment]
We can but should we have multiple files? We could have it in one file with comments i.e.

```
plugin "terraform" {
  enabled = true
  # or "all" which will include below optional rules
  preset  = "recommended"
}
```

If we have `.tflint-module.hcl` and `.tflint-all.hcl` how would we describe in the documentation which one a first time user should look into  / use.

**Comment by mhmdio** [comment]
+1 for the recommended one, I did not know about it, we can add two sections:

1. recommended rules
2. all rules

**Comment by sthuber90** [comment]
Do the most recent changes work for you?

**Comment by mhmdio** [comment]
Yes, looks nicer even.

we need a way to download a release, maybe two zip files in a release one for recommended and one for all. so with simple curl we can access both from any CI

**Comment by sthuber90** [comment]
@mhmdio I think I've added all requested changes. Please have a look and feel free to merge if you agree 🚀

**Comment by mhmdio** [comment]
LGTM, thank you for the nice addition

**Pull request merged**
